name: mobile_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^1.0.4
  group_radio_button: ^1.0.1
  grouped_buttons: ^1.0.4
  fluttertoast: ^2.0.7
  badges: ^1.1.1
  background_app_bar: ^1.0.2
  flutter_multiselect: ^0.5.0


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - images/4.jpg
    - images/5.jpg
